bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "reloaded tmux config"

set-option -g prefix F12

# splits 
bind-key v split-window
bind-key h split-window -h

# colors
set-option -g pane-border-style bg=default
set-option -g pane-border-style bg=default
set-option -g status-style bg=black
set-option -g message-style fg=yellow,bright
set-option -g display-panes-active-colour colour3
set-option -g display-panes-colour colour166
set-option -g clock-mode-colour colour166

set -g status-interval 1
set -g status-justify centre
set -g status-left-length 10
set -g status-right-length 140
set -g status-left ""
set -g status-right ""

set -s escape-time 0 # faster key repetition

setw -g aggressive-resize on

# twm
bind f run-shell "tmux neww twm"
# bind F run-shell "tmux neww twm -l"
bind s run-shell "tmux neww twm -e"
bind g run-shell "tmux neww twm -g"
# bind e run-shell "tmux switch -t $TWM_DEFAULT"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# file picker
set -g @plugin 'tmux-plugins/tmux-fpp'
set -g @fpp-bind off # disables `prefix + f`
set -g @fpp-path '~/.config/tmux/plugins/tmux-fpp/fpp.tmux'
bind Space run-shell '~/.config/tmux/plugins/tmux-fpp/fpp.tmux start edit'

# floating terminal
set -g @plugin "lloydbond/tmux-floating-terminal"
set -g @floating_scratch_term 'i'
# TODO:
# set -g @floating_scratch_to_active_win 'M-h'
# set -g @floating_scratch_to_win 'M-l'
# set -g @floating_active_pane_to_scratch 'M-m'

# copying and pasting
set -g @plugin 'Morantron/tmux-fingers'

# saving sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
